"""add_token_metadata_columns

Revision ID: 04d2bae069d3
Revises: 14376c0b4e95
Create Date: 2026-02-18 18:57:07.531293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d2bae069d3'
down_revision: Union[str, Sequence[str], None] = '14376c0b4e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('tokens', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('tokens', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('tokens', sa.Column('twitter', sa.String(length=500), nullable=True))
    op.add_column('tokens', sa.Column('telegram', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'telegram')
    op.drop_column('tokens', 'twitter')
    op.drop_column('tokens', 'website')
    op.drop_column('tokens', 'description')
    op.drop_column('tokens', 'image_url')
    # ### end Alembic commands ###
