"""add_damm_tvl_volume_columns

Revision ID: 14376c0b4e95
Revises: d39f168b79cd
Create Date: 2026-02-18 17:52:50.564031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14376c0b4e95'
down_revision: Union[str, Sequence[str], None] = 'd39f168b79cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('dbc_damm_tvl', sa.Numeric(), nullable=True))
    op.add_column('tokens', sa.Column('dbc_damm_volume', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'dbc_damm_volume')
    op.drop_column('tokens', 'dbc_damm_tvl')
    # ### end Alembic commands ###
