"""create_initial_tables

Revision ID: 2ea80474a853
Revises: 
Create Date: 2026-02-17 11:00:49.334424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea80474a853'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('win_rate', sa.Numeric(), nullable=True),
    sa.Column('avg_profit_pct', sa.Numeric(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('total_pnl_usd', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'chain', name='uq_token_address_chain')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(length=64), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=True),
    sa.Column('current_price', sa.Numeric(), nullable=True),
    sa.Column('amount_token', sa.Numeric(), nullable=True),
    sa.Column('amount_sol_invested', sa.Numeric(), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(), nullable=False),
    sa.Column('pnl_usd', sa.Numeric(), nullable=False),
    sa.Column('max_price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_paper', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_status', 'positions', ['status'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('token_price_at_signal', sa.Numeric(), nullable=True),
    sa.Column('token_mcap_at_signal', sa.Numeric(), nullable=True),
    sa.Column('liquidity_at_signal', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('is_open_source', sa.Boolean(), nullable=True),
    sa.Column('is_proxy', sa.Boolean(), nullable=True),
    sa.Column('is_mintable', sa.Boolean(), nullable=True),
    sa.Column('lp_burned', sa.Boolean(), nullable=True),
    sa.Column('lp_locked', sa.Boolean(), nullable=True),
    sa.Column('lp_lock_duration_days', sa.Integer(), nullable=True),
    sa.Column('contract_renounced', sa.Boolean(), nullable=True),
    sa.Column('top10_holders_pct', sa.Numeric(), nullable=True),
    sa.Column('dev_holds_pct', sa.Numeric(), nullable=True),
    sa.Column('dev_token_balance', sa.Numeric(), nullable=True),
    sa.Column('is_honeypot', sa.Boolean(), nullable=True),
    sa.Column('buy_tax', sa.Numeric(), nullable=True),
    sa.Column('sell_tax', sa.Numeric(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    op.create_table('token_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('liquidity_usd', sa.Numeric(), nullable=True),
    sa.Column('volume_5m', sa.Numeric(), nullable=True),
    sa.Column('volume_1h', sa.Numeric(), nullable=True),
    sa.Column('volume_24h', sa.Numeric(), nullable=True),
    sa.Column('holders_count', sa.Integer(), nullable=True),
    sa.Column('top10_holders_pct', sa.Numeric(), nullable=True),
    sa.Column('dev_holds_pct', sa.Numeric(), nullable=True),
    sa.Column('smart_wallets_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_token_time', 'token_snapshots', ['token_id', 'timestamp'], unique=False)
    op.create_table('wallet_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('token_address', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('amount_sol', sa.Numeric(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(), nullable=True),
    sa.Column('amount_token', sa.Numeric(), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['smart_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_activity_time', 'wallet_activity', ['timestamp'], unique=False)
    op.create_index('idx_wallet_activity_wallet', 'wallet_activity', ['wallet_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('amount_sol', sa.Numeric(), nullable=True),
    sa.Column('amount_token', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('slippage_pct', sa.Numeric(), nullable=True),
    sa.Column('fee_sol', sa.Numeric(), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('is_paper', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_time', 'trades', ['executed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_time', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_wallet_activity_wallet', table_name='wallet_activity')
    op.drop_index('idx_wallet_activity_time', table_name='wallet_activity')
    op.drop_table('wallet_activity')
    op.drop_index('idx_snapshots_token_time', table_name='token_snapshots')
    op.drop_table('token_snapshots')
    op.drop_table('token_security')
    op.drop_table('signals')
    op.drop_index('idx_positions_status', table_name='positions')
    op.drop_table('positions')
    op.drop_table('tokens')
    op.drop_table('smart_wallets')
    # ### end Alembic commands ###
