"""add_trade_counts_and_birdeye_fields

Revision ID: 2ee0cdb2e014
Revises: f1527bad7baf
Create Date: 2026-02-18 16:57:19.239696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee0cdb2e014'
down_revision: Union[str, Sequence[str], None] = 'f1527bad7baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_snapshots', sa.Column('buys_5m', sa.Integer(), nullable=True))
    op.add_column('token_snapshots', sa.Column('sells_5m', sa.Integer(), nullable=True))
    op.add_column('token_snapshots', sa.Column('buys_1h', sa.Integer(), nullable=True))
    op.add_column('token_snapshots', sa.Column('sells_1h', sa.Integer(), nullable=True))
    op.add_column('token_snapshots', sa.Column('buys_24h', sa.Integer(), nullable=True))
    op.add_column('token_snapshots', sa.Column('sells_24h', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_snapshots', 'sells_24h')
    op.drop_column('token_snapshots', 'buys_24h')
    op.drop_column('token_snapshots', 'sells_1h')
    op.drop_column('token_snapshots', 'buys_1h')
    op.drop_column('token_snapshots', 'sells_5m')
    op.drop_column('token_snapshots', 'buys_5m')
    # ### end Alembic commands ###
