"""add_ohlcv_and_trades_tables

Revision ID: 653dabb4e148
Revises: 2ee0cdb2e014
Create Date: 2026-02-18 17:33:27.098212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653dabb4e148'
down_revision: Union[str, Sequence[str], None] = '2ee0cdb2e014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'timestamp', 'interval', name='uq_ohlcv_token_time_interval')
    )
    op.create_index('idx_ohlcv_token_time', 'token_ohlcv', ['token_id', 'timestamp'], unique=False)
    op.create_table('token_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price_usd', sa.Numeric(), nullable=True),
    sa.Column('amount_token', sa.Numeric(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(), nullable=True),
    sa.Column('amount_sol', sa.Numeric(), nullable=True),
    sa.Column('wallet_address', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_token_time', 'token_trades', ['token_id', 'timestamp'], unique=False)
    op.create_index('idx_trades_wallet', 'token_trades', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_wallet', table_name='token_trades')
    op.drop_index('idx_trades_token_time', table_name='token_trades')
    op.drop_table('token_trades')
    op.drop_index('idx_ohlcv_token_time', table_name='token_ohlcv')
    op.drop_table('token_ohlcv')
    # ### end Alembic commands ###
