"""expand_enrichment_pipeline

Revision ID: 76bb616addf5
Revises: 2ea80474a853
Create Date: 2026-02-18 11:02:11.185771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bb616addf5'
down_revision: Union[str, Sequence[str], None] = '2ea80474a853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('initial_mcap', sa.Numeric(), nullable=True),
    sa.Column('peak_mcap', sa.Numeric(), nullable=True),
    sa.Column('peak_price', sa.Numeric(), nullable=True),
    sa.Column('peak_multiplier', sa.Numeric(), nullable=True),
    sa.Column('time_to_peak_sec', sa.Integer(), nullable=True),
    sa.Column('final_mcap', sa.Numeric(), nullable=True),
    sa.Column('final_multiplier', sa.Numeric(), nullable=True),
    sa.Column('peak_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('is_rug', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['peak_snapshot_id'], ['token_snapshots.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    op.create_table('token_top_holders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.Column('percentage', sa.Numeric(), nullable=True),
    sa.Column('pnl', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['token_snapshots.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_top_holders_snapshot', 'token_top_holders', ['snapshot_id'], unique=False)
    op.create_index('idx_top_holders_token', 'token_top_holders', ['token_id'], unique=False)
    op.add_column('token_snapshots', sa.Column('stage', sa.String(length=20), nullable=True))
    op.add_column('token_snapshots', sa.Column('dex_price', sa.Numeric(), nullable=True))
    op.add_column('token_snapshots', sa.Column('dex_liquidity_usd', sa.Numeric(), nullable=True))
    op.add_column('token_snapshots', sa.Column('dex_volume_5m', sa.Numeric(), nullable=True))
    op.add_column('token_snapshots', sa.Column('dex_volume_1h', sa.Numeric(), nullable=True))
    op.add_column('token_snapshots', sa.Column('dex_volume_24h', sa.Numeric(), nullable=True))
    op.add_column('token_snapshots', sa.Column('dex_fdv', sa.Numeric(), nullable=True))
    op.add_column('tokens', sa.Column('creator_address', sa.String(length=64), nullable=True))
    op.add_column('tokens', sa.Column('initial_buy_sol', sa.Numeric(), nullable=True))
    op.add_column('tokens', sa.Column('initial_mcap_sol', sa.Numeric(), nullable=True))
    op.add_column('tokens', sa.Column('bonding_curve_key', sa.String(length=64), nullable=True))
    op.add_column('tokens', sa.Column('v_sol_in_bonding_curve', sa.Numeric(), nullable=True))
    op.add_column('tokens', sa.Column('v_tokens_in_bonding_curve', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'v_tokens_in_bonding_curve')
    op.drop_column('tokens', 'v_sol_in_bonding_curve')
    op.drop_column('tokens', 'bonding_curve_key')
    op.drop_column('tokens', 'initial_mcap_sol')
    op.drop_column('tokens', 'initial_buy_sol')
    op.drop_column('tokens', 'creator_address')
    op.drop_column('token_snapshots', 'dex_fdv')
    op.drop_column('token_snapshots', 'dex_volume_24h')
    op.drop_column('token_snapshots', 'dex_volume_1h')
    op.drop_column('token_snapshots', 'dex_volume_5m')
    op.drop_column('token_snapshots', 'dex_liquidity_usd')
    op.drop_column('token_snapshots', 'dex_price')
    op.drop_column('token_snapshots', 'stage')
    op.drop_index('idx_top_holders_token', table_name='token_top_holders')
    op.drop_index('idx_top_holders_snapshot', table_name='token_top_holders')
    op.drop_table('token_top_holders')
    op.drop_table('token_outcomes')
    # ### end Alembic commands ###
