"""add_performance_indexes

Revision ID: 9dfac8341079
Revises: ab067807286b
Create Date: 2026-02-18 21:25:00.514786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfac8341079'
down_revision: Union[str, Sequence[str], None] = 'ab067807286b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_signals_status_created', 'signals', ['status', 'created_at'], unique=False)
    op.create_index('idx_signals_token', 'signals', ['token_id'], unique=False)
    op.create_index('idx_snapshots_timestamp', 'token_snapshots', ['timestamp'], unique=False)
    op.create_index('idx_tokens_creator', 'tokens', ['creator_address'], unique=False)
    op.create_index('idx_tokens_source', 'tokens', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tokens_source', table_name='tokens')
    op.drop_index('idx_tokens_creator', table_name='tokens')
    op.drop_index('idx_snapshots_timestamp', table_name='token_snapshots')
    op.drop_index('idx_signals_token', table_name='signals')
    op.drop_index('idx_signals_status_created', table_name='signals')
    # ### end Alembic commands ###
