"""add_signal_outcome_columns

Revision ID: ab067807286b
Revises: 04d2bae069d3
Create Date: 2026-02-18 21:21:06.270627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab067807286b'
down_revision: Union[str, Sequence[str], None] = '04d2bae069d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('peak_roi_pct', sa.Numeric(), nullable=True))
    op.add_column('signals', sa.Column('peak_multiplier_after', sa.Numeric(), nullable=True))
    op.add_column('signals', sa.Column('is_rug_after', sa.Boolean(), nullable=True))
    op.add_column('signals', sa.Column('outcome_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'outcome_updated_at')
    op.drop_column('signals', 'is_rug_after')
    op.drop_column('signals', 'peak_multiplier_after')
    op.drop_column('signals', 'peak_roi_pct')
    # ### end Alembic commands ###
