"""add_creator_profiles_table

Revision ID: d39f168b79cd
Revises: 653dabb4e148
Create Date: 2026-02-18 17:36:55.775190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39f168b79cd'
down_revision: Union[str, Sequence[str], None] = '653dabb4e148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('total_launches', sa.Integer(), nullable=False),
    sa.Column('rugged_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('avg_peak_multiplier', sa.Numeric(), nullable=True),
    sa.Column('avg_time_to_peak_sec', sa.Integer(), nullable=True),
    sa.Column('last_launch_at', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creator_profiles')
    # ### end Alembic commands ###
