"""add_meteora_dbc_columns

Revision ID: f1527bad7baf
Revises: 76bb616addf5
Create Date: 2026-02-18 14:30:32.382479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1527bad7baf'
down_revision: Union[str, Sequence[str], None] = '76bb616addf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('dbc_pool_address', sa.String(length=64), nullable=True))
    op.add_column('tokens', sa.Column('dbc_quote_reserve', sa.Numeric(), nullable=True))
    op.add_column('tokens', sa.Column('dbc_launchpad', sa.String(length=50), nullable=True))
    op.add_column('tokens', sa.Column('dbc_is_migrated', sa.Boolean(), nullable=True))
    op.add_column('tokens', sa.Column('dbc_migration_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'dbc_migration_timestamp')
    op.drop_column('tokens', 'dbc_is_migrated')
    op.drop_column('tokens', 'dbc_launchpad')
    op.drop_column('tokens', 'dbc_quote_reserve')
    op.drop_column('tokens', 'dbc_pool_address')
    # ### end Alembic commands ###
